knp_gaufrette:
    adapters:
        app_image:
            local:
                directory: "%kernel.project_dir%/public/media/image"
                create: true
    filesystems:
        app_image:
            adapter: "app_image"

    stream_wrapper: ~